import { Project } from "@/types";


export const PROJECTS: Project[] = [
    {
        id: "1",
        nombre: "Decó Polo",
        image: "/assets/images/proyectos/deco-polo.png",
        imagenVertical: "/assets/images/proyectos/vertical-1.png",
        logo: "/assets/images/proyectos/abv.png",
        desarrollador: "ABV Arquitectura",
        ubicacion: "Palermo, Buenos Aires",
        ubicacionType: "CABA",
        roi: "12-15% Anual",
        valorRoi: 15,
        minTicket: 120000,
        inversionMinima: 100,
        status: "Pre-venta",
        porcentajeFinanciacion: 20,
        plazo: 36,
        tags: ["Pre-venta", "Riesgo: Bajo"],
        risk: "Bajo",
        proyectosCompletados: 5,
        montoGestionado: "+ $50M gestionados.",
        stars: 4.5,
        resumen: "Decó Polo presenta una nueva experiencia high-end en Buenos Aires, generando un nuevo legado en la ciudad.La arquitectura, el diseño y la naturaleza se unen de manera armónica para crear un espacio con identidad propia. Geometrías, juegos entre rectas y curvas sutiles. Cada detalle refleja sofisticación y funcionalidad.",
        brochure: "https://abv.com.ar/proyectos/deco-polo/",
    },
    {
        id: "2",
        nombre: "Mirabilia Hype",
        image: "/assets/images/proyectos/mirabilia-hype.png",
        imagenVertical: "/assets/images/proyectos/vertical-2.png",
        logo: "/assets/images/proyectos/mirabilia.png",
        desarrollador: "Mirabilia",
        ubicacion: "Chacarita, CABA, Buenos Aires.",
        ubicacionType: "CABA",
        roi: "12-15% Anual",
        valorRoi: 15,
        minTicket: 150000,
        inversionMinima: 100,
        status: "Construcción",
        porcentajeFinanciacion: 80,
        plazo: 36,
        tags: ["Construcción", "Riesgo: Medio"],
        risk: "Medio",
        proyectosCompletados: 17,
        montoGestionado: "+ $50M gestionados.",
        stars: 4.5,
        resumen: "Un nuevo complejo residencial que fusiona naturaleza y modernidad en un equilibrio perfecto. Mirabilia Hype ofrece amenities exclusivos: 4 piscinas climatizadas, un gimnasio equipado con la tecnología más avanzada, espacio polideportivo cubierto, sectores para la relajación y una renovada oferta gastronómica. Cuenta con 4.000m2 de pulmón verde, el complejo ofrece unidades de 1, 2, 3 y 4 dormitorios, con superficies que van desde los 55 m² hasta los 285 m², adaptándose a diferentes estilos de vida.",
        brochure: "https://mirabiliahype.com/wp-content/uploads/2025/10/Brochure_M_Hype_2025_dig.pdf",
    },
    {
        id: "3",
        nombre: "Open Buenavista",
        image: "/assets/images/proyectos/open-buenavista.png",
        imagenVertical: "/assets/images/proyectos/vertical-3.png",
        logo: "/assets/images/proyectos/portland.png",
        desarrollador: "Portland",
        ubicacion: "Don Francisco y Av. Uruguay, San Fernando, Argentina.",
        ubicacionType: "Interior",
        roi: "12-15% Anual",
        valorRoi: 15,
        minTicket: 100000,
        inversionMinima: 100,
        status: "Planificación",
        porcentajeFinanciacion: 100,
        plazo: 36,
        tags: ["Planificación", "Riesgo: Bajo"],
        risk: "Bajo",
        proyectosCompletados: 17,
        montoGestionado: "+ $50M gestionados.",
        stars: 4,
        resumen: "Ubicado en un punto estratégico de Acceso Norte y rodeado de comercios, deporte, gastronomía y servicios. OPEN Buenavista te permite moverte fácil, trabajar con comodidad y disfrutar cada momento con más libertad. Un proyecto de cuatro edificios, PB + 8 pisos, con unidades de categoría de 2, 3 y 4 ambientes. Superficies amplias y balcones aterrazados que amplían la experiencia de vivir adentro y afuera. OPEN propone un estilo de vida auténtico, flexible y lleno de posibilidades.",
        brochure: "https://drive.google.com/file/d/1D5nkyWjlVQ9pNowLO39CNBt_KnuqSrGo/view",
    },
    {
        id: "4",
        nombre: "Nómada Parque",
        image: "/assets/images/proyectos/nomada-parque.png",
        imagenVertical: "/assets/images/proyectos/vertical-4.png",
        logo: "/assets/images/proyectos/grupo-nomada.png",
        desarrollador: "Grupo Nómada",
        ubicacion: "Nuñez, CABA, Argentina",
        ubicacionType: "CABA",
        roi: "12-15% Anual",
        valorRoi: 15,
        minTicket: 80000,
        inversionMinima: 100,
        status: "Pre-venta",
        porcentajeFinanciacion: 60,
        plazo: 36,
        tags: ["Pre-venta", "Riesgo: Alto"],
        risk: "Alto",
        proyectosCompletados: 13,
        montoGestionado: "+ $50M gestionados.",
        stars: 4,
        resumen: "Más de 20.000 m² destinados a la construcción de un novedoso proyecto en Parque de Innovación, en el barrio de Núñez, una de las zonas más distinguidas de la Ciudad Autónoma de Buenos Aires. Este desarrollo residencial presenta más de 750 m² dedicados a locales comerciales y gastronómicos, terraza con espejo de agua y vegetación, y más de 400 m² de amenities. ✓ Parking comercial✓ 3 subsuelos de cocheras✓ Propuesta de servicios y experiencias a través de nuestro programa ALDEA®",
        brochure: "https://grupoportland.com/wp-content/uploads/2023/06/Brochure-Nova-impreso-06.pdf",
    },
        {
        id: "5",
        nombre: "One Residential Tower",
        image: "/assets/images/proyectos/one-residential-tower.png",
        imagenVertical: "/assets/images/proyectos/vertical-5.png",
        logo: "/assets/images/proyectos/tsf.png",
        desarrollador: "TSF Desarrollos",
        ubicacion: "Avenida Maipú, Vicente López, CABA",
        ubicacionType: "CABA",
        roi: "12,5% Anual",
        valorRoi: 12.5,
        minTicket: 80000,
        inversionMinima: 100,
        status: "Pre-venta",
        porcentajeFinanciacion: 50,
        plazo: 36,
        tags: ["Pre-venta", "Riesgo: Alto"],
        risk: "Alto",
        proyectosCompletados: 13,
        montoGestionado: "+ $50M gestionados.",
        stars: 4,   
        resumen: "One Residential Tower es un excepcional desarrollo inmobiliario ubicado estraté-gicamente en un lote de 1200 m2 en el corredor de la avenida Maipú en Vicente López. Este proyecto se destaca por ofre-cer 90 unidades de 2 y 3 ambientes, que varían en tamaño de 55 a 93 m2. Cada unidad ha sido cuidadosamente diseñada para ofrecer una experiencia de vida premium. ONE Residential Tower se alza en Vicente López, rodeado de áreas verdes y a solo unas cuadras del Río de la Plata, con vistas panorámicas y la serenidad de este entorno único.",
        brochure: "https://tsfdesarrollos.com/wp-content/uploads/2023/10/One-Brochure.pdf",
    },
];

export const FILTER_OPTIONS = {
    ubicacion: ["CABA", "Interior", "Otro"],
    estado: ["Obra - Avanzado", "Obra - Comienzo", "Terminado", "Planificación", "Pre-venta", "Construcción"],
    roi: ["25%", "50%", "13%", "12-15%"],
    plazo: ["12 meses", "18 meses", "24 meses", "36 meses"],
};

export const DESARROLLADORES = [
    {
        id: "1",
        nombre: "ABV Arquitectura",
        logo: "/assets/images/proyectos/abv.png",
        proyectos: 54,
        montoGestionado: "+ $50M gestionados.",
        rating: 4.5,
        descripcion: "ABV es una empresa de arquitectura con sede en Argentina y especializada en inversiones inmobiliarias. Cuenta con más de 35 años de trayectoria. Ha desarrollado más de 54 emprendimientos propios y para inversores en diversas escalas. Las inversiones inmobiliarias desarrolladas por el grupo han sido éxito de ventas y han representado importantes tasas de retorno para el inversor.",
    },
    {
        id: "2",
        nombre: "Mirabilia",
        logo: "/assets/images/proyectos/mirabilia.png",
        proyectos: 17,
        montoGestionado: "+ $50M gestionados.",
        rating: 4.5,
        descripcion: "Somos arquitectos que desarrollamos nuestros productos de principio a fin, con la responsabilidad y el respeto que nos genera ser conscientes del impacto futuro de todo lo que hacemos hoy. Creemos que la buena arquitectura y el buen desarrollo logran productos que se valorizan con el tiempo, y a la vez revaloriza su entorno. Tenemos más de 38 años en el mercado. "
    },
    {
        id: "3",
        nombre: "Portland",
        logo: "/assets/images/proyectos/portland.png",  
        proyectos: 17,
        montoGestionado: "+ $50M gestionados.",
        rating: 4.5,
        descripcion: "Más de 20 años de experiencia en el mercado de la construcción. Somos una empresa constructora y desarrolladora, innovadora y disruptiva. Nuestro equipo de profesionales lo acompañan en cada etapa del proceso y adaptan los recursos a la medida de sus necesidades. Desde la locación hasta la comercialización del proyecto. Ideamos tus espacios.Construimos el futuro. Creamos experiencias "
    },
    {
        id: "4",
        nombre: "Grupo Nómada",
        logo: "/assets/images/proyectos/grupo-nomada.png",  
        proyectos: 17,
        montoGestionado: "+ $50M gestionados.",
        rating: 4.5,
        descripcion: "Desde hace más de una década, nos enfocamos en el desarrollo inmobiliario de edificios de alto impacto, dedicándonos a la creación de entornos distintivos que incluyen espacios corporativos, residenciales, hoteleros y comerciales en Argentina, España y Estados Unidos. Abarcamos todas las etapas del proceso: identificamos tierra, proyectamos, dirigimos, gestionamos y comercializamos cada una de nuestras obras, demostrando un fuerte compromiso con el diseño y la calidad constructiva."
    },
    {
        id: "5",
        nombre: "TSF Desarrollos",
        logo: "/assets/images/proyectos/tsf.png",
        proyectos: 13,
        montoGestionado: "+ $50M gestionados.",
        rating: 4.5,
        descripcion: "Realizamos desarrollos inmobiliarios de alta calidad constructiva para clientes que buscan un diferencial. Afianzamos el ejercicio de una práctica arquitectónica colaborativa, desarrollando un amplio abanico de proyectos. Combinando creatividad y profesionalidad, abarcamos los campos de la arquitectura, el urbanismo y el diseño de interiores, dominando todas las fases del proceso del proyecto, desde los estudios preliminares hasta la finalización y la supervisión de la obra."
    },
];
